version: '3.3'
services:
  database:
    image: mysql:8
    container_name: mysql-docker
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
